/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jitsi_impl_neomedia_codec_audio_speex_Speex */

#ifndef _Included_org_jitsi_impl_neomedia_codec_audio_speex_Speex
#define _Included_org_jitsi_impl_neomedia_codec_audio_speex_Speex
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jitsi_impl_neomedia_codec_audio_speex_Speex
 * Method:    bits_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_audio_speex_Speex_bits_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_audio_speex_Speex
 * Method:    bits_init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_codec_audio_speex_Speex_bits_1init
  (JNIEnv *, jclass);

/*
 * Class:     org_jitsi_impl_neomedia_codec_audio_speex_Speex
 * Method:    bits_nbytes
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_codec_audio_speex_Speex_bits_1nbytes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_audio_speex_Speex
 * Method:    bits_read_from
 * Signature: (J[BII)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_audio_speex_Speex_bits_1read_1from
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_audio_speex_Speex
 * Method:    bits_remaining
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_codec_audio_speex_Speex_bits_1remaining
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_audio_speex_Speex
 * Method:    bits_reset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_audio_speex_Speex_bits_1reset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_audio_speex_Speex
 * Method:    bits_write
 * Signature: (J[BII)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_codec_audio_speex_Speex_bits_1write
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_audio_speex_Speex
 * Method:    decode_int
 * Signature: (JJ[SI)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_codec_audio_speex_Speex_decode_1int
  (JNIEnv *, jclass, jlong, jlong, jshortArray, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_audio_speex_Speex
 * Method:    decoder_ctl
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_codec_audio_speex_Speex_decoder_1ctl__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_audio_speex_Speex
 * Method:    decoder_ctl
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_codec_audio_speex_Speex_decoder_1ctl__JII
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_audio_speex_Speex
 * Method:    decoder_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_audio_speex_Speex_decoder_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_audio_speex_Speex
 * Method:    decoder_init
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_codec_audio_speex_Speex_decoder_1init
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_audio_speex_Speex
 * Method:    encode_int
 * Signature: (J[SIJ)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_codec_audio_speex_Speex_encode_1int
  (JNIEnv *, jclass, jlong, jshortArray, jint, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_audio_speex_Speex
 * Method:    encoder_ctl
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_codec_audio_speex_Speex_encoder_1ctl__JI
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_audio_speex_Speex
 * Method:    encoder_ctl
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_codec_audio_speex_Speex_encoder_1ctl__JII
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_audio_speex_Speex
 * Method:    encoder_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_audio_speex_Speex_encoder_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_audio_speex_Speex
 * Method:    encoder_init
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_codec_audio_speex_Speex_encoder_1init
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_audio_speex_Speex
 * Method:    lib_get_mode
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_codec_audio_speex_Speex_lib_1get_1mode
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_audio_speex_Speex
 * Method:    resampler_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_audio_speex_Speex_resampler_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_audio_speex_Speex
 * Method:    resampler_init
 * Signature: (IIIIJ)J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_codec_audio_speex_Speex_resampler_1init
  (JNIEnv *, jclass, jint, jint, jint, jint, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_audio_speex_Speex
 * Method:    resampler_process_interleaved_int
 * Signature: (JLjava/lang/Object;IILjava/lang/Object;II)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_codec_audio_speex_Speex_resampler_1process_1interleaved_1int
  (JNIEnv *, jclass, jlong, jobject, jint, jint, jobject, jint, jint);

/*
 * Class:     org_jitsi_impl_neomedia_codec_audio_speex_Speex
 * Method:    resampler_set_rate
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_codec_audio_speex_Speex_resampler_1set_1rate
  (JNIEnv *, jclass, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
